version: "3"
services:
  kokkoro-bot:
    image: kokkoro-env:latest
    ports:
      - "5001:5001"
    expose:
      - 8080
    volumes:
      - ./:/bot/
      - ~/.kokkoro:/root/.kokkoro
    command: python3.8 -u /bot/run.py